---
title: "data_wrangling"
output: html_document
---

```{r}
library(tidyverse) # install.packages("tidyverse")
```

```{r}
## read gapminder csv. Note the readr:: prefix identifies which package it's in
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

#inspect the data
gapminder     #looks at all of the data (you can also look by clicking in global envt)
head(gapminder)   #looks at first 6
head(gapminder, 10)
tail(gapminder)
tail(gapminder, 15)

#summary stats
str(gapminder)
summary(gapminder) #tells you min, max, mean, etc--glance at variables, not really useful if not numeric

#install.packages("skimr")
library(skimr)
skimr::skim(gapminder) #skimr::skim syntax is more for personal reminder 
#tells you more stats--stdev, percentiles...more?

names(gapminder) #returns column names in case you need to batch rename them
dim(gapminder)  #tells you dimensions -- rows and columns of the set
ncol(gapminder) #number of columns
nrow(gapminder) #number of rows

#reverse-engineer dim function
c(nrow(gapminder), ncol(gapminder)) #concatenates number of rows and columns

```

## Dplyr!

```{r}
# most used functions are filter(), select(), mutate(), summarize(), arrange()
# first argument is always the data, subsequent args are what you want to do with it
# you can refer to columns in dataframe without using $, which is kinda messy (but I like it!)
# the result is a new df

# filter by rows
filter(gapminder, lifeExp < 29) # subset based on life exp < 29
# gives entire df back based on arguments
filter(gapminder, country == "Mexico")
filter(gapminder, country %in% c("Mexico", "Peru", "Brazil")) # using %in% allows filter() to search more than one argument/return a list
filter(gapminder, country == "Mexico", year == 2002)

#find mean lifeExp of Sweden
sweden <- filter(gapminder, country == "Sweden")
average <- mean(sweden$lifeExp)
average
```

```{r}
#select by columns
select(gapminder, year, lifeExp)  # select only these columns
select(gapminder, -continent, -liftExp) # - will exclude these columns

# use select and filter together
gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia
gap_cambodia2 <- select(gap_cambodia, -continent, - lifeExp)
gap_cambodia2
# the above is hella wordy
#time to learn about the pipe operator--it will change your life
```


```{r}
gapminder %>% head(3)  # this is equivalent to head(gapminder, 3) -- not super impressive

gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, - lifeExp)

gap_cambodia <- gapminder %>% filter(country == "Cambodia")
gap_cambodia2 <- gap_cambodia %>% select(-continent, -lifeExp) #  still wordy

gap_cambodia <- gapminder %>%         # much clearer
  filter(country == "Cambodia") %>%
  select(-continent, -lifeExp)
gap_cambodia

```


```{r}
# mutate adds new variables
gapminder %>% 
  mutate(numbers = 1:nrow(gapminder)) # adds a column index for each row

gapminder %>% 
  mutate(planet = "Earth")

gapminder %>% 
  mutate(gdp = pop * gdpPercap)
```

```{r}
# find the max gdp per cap of Egypt and Vietnam and create a new column

egviet <- gapminder %>% 
  filter(country %in% c("Egypt", "Vietnam"))

max(egviet$gdpPercap)

gapminder %>% mutate(max_of_egy_viet = 5581.181)

# slightly different exercise
gapminder %>% 
  filter(country %in% c("Egypt", "Vietnam")) %>% 
  mutate(gdp = pop * gdpPercap) %>% 
  mutate(max_gdp = max(gdp))


gapminder %>% 
  filter(country %in% c("Egypt", "Vietnam")) %>% 
  mutate(gdp = pop * gdpPercap, 
          max_gdp = max(gdp))
```

## group_by() groups

```{r}
## with mutate()
new_gap <- gapminder %>%  # group by country, then apply a function to those groups, then ungroup
  group_by(country) %>%   # allows you to do it by study site or by day or something
  mutate(gdp = gdpPercap * pop,
         max_gdp = max(gdp)) %>% 
  ungroup()

##with summarize
gap_summed <- gapminder %>%  # group by country, then apply a function to those groups, then ungroup
  group_by(country) %>%   # allows you to do it by study site or by day or something
  mutate(gdp = gdpPercap * pop) %>% 
  summarize(max_gdp = max(gdp)) %>% 
  ungroup()
```

## 'arrange()' arranges columns
```{r}
gap_arranged <- gapminder %>%  
  group_by(country) %>%   
  mutate(gdp = gdpPercap * pop) %>% 
  summarize(max_gdp = max(gdp)) %>% 
  ungroup() %>% 
  arrange(desc(max_gdp)) ## default setting for arrange() is in ascending order--desc() flips it

```

## joining datasets
```{r}
#left_join keeps everything from the left table and matches as much as it can from the right table. In R, the first thing that you type will be the left table (because it’s on the left)
#right_join keeps everything from the right table and matches as much as it can from the left table
#inner_join only keeps the observations that are similar between the two tables
#full_join keeps all observations from both tables.

## read in the data. (same URL as yesterday, with co2.csv instead of gapminder.csv)
co2 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv")

## explore
co2 %>% head()
co2 %>% dim() # 12

## create new variable that is only 2007 data
gap_2007 <- gapminder %>%
  filter(year == 2007) 
gap_2007 %>% dim() # 142  

new_2007 <- gapminder %>%   # practice
  filter(year == 2007)
new_2007 %>% dim()

## left_join gap_2007 to co2
lj <- left_join(gap_2007, co2, by="country")

left <- left_join(new_2007, co2, by = "country") # messing around

right <- right_join(new_2007, co2, by = "country")  # messing around

no_na_join <- inner_join(new_2007, co2, by="country") #wanted to have no "NA" cells

## explore
lj %>% dim() #142
lj %>% summary() # lots of NAs in the co2_2017 columm
lj %>% View() 

## right_join gap_2007 and co2
rj <- right_join(gap_2007, co2) # this will work--R will look between column names and see where they can match up--however, it's not a great idea to do this because it makes the code less clear



## explore
rj %>% dim() # 12
rj %>% summary()
rj %>% View() 

```















