---
title: "graphics_w_ggplot2"
author: "Daniel"
date: "10/22/18"
output: html_document
---

www.github.com
[GitHub]www.github.com

# Learning ggplot2

We're learning ggplot2 and it's going to be great.


```{r}

#install packages
#install.packages("tidyverse")
library(tidyverse)
```


```{r load_data}
#National Parks in California
ca <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/ca.csv") 

#Acadia National Park
acadia <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/acadia.csv")

#Southeast US National Parks
se <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/mass.csv")
```

Start with California ('ca') dataset

Plot visitation to all CA National Parks over time

```{r}
ggplot(ca, aes(year, visitors)) +
  geom_point(aes(color = park_name)) +
  labs(x = "Year",  #labels
       y = "Visitation", 
       title = "California National Park Visitation")+
  theme_bw() + #changes background to black and white
  theme(legend.title = element_blank()) + #gets rid of legend title
  theme(plot.title = element_text(hjust = 0.5)) #centers plot title
```

```{r}
ggplot(se, aes(year, visitors)) +
  geom_point(aes(color = state)) +
  xlab("Year") +
  ylab("Visitation") +
  ggtitle("Visitation to Southeastern National Parks") +
  theme(legend.title = element_blank(),
      axis.text.x = element_text(angle = 45, hjust = 1, size = 14)) +
  theme_minimal()
  

```


```{r}
ggplot(se, aes(year, visitors, color = park_name)) +
  geom_point() +
  facet_wrap(~ state, scales = "free") + #scales attribute separates the axis scales in each plot
  theme(axis.text.x = element_text(angle = 90)) #otherwise NC makes the others trapped on a small scale
```

```{r}
ggplot(se, aes(park_name, visitors, color = "park_name"))+
  geom_jitter(alpha = 0.4, width = 0.1) +
  coord_flip()+
  xlab("Visitors") +
  ylab("Park Name") +
  ggtitle("Visitors to Southeastern Parks")
```


```{r}
ggplot(se, aes(year, visitors, color = park_name))+
  geom_line(size = 1.6)+
  theme_bw()+
  ggtitle("Visitors")+
  theme(plot.title = element_text(hjust = 0.5)) #centers plot title
  
```

```{r}
ggplot(acadia, aes(year, visitors))+
  geom_point()+
  geom_line()+
  geom_smooth(aes(color = "red"))
```


# Bar Charts

```{r}
ggplot(visit_16, aes(state, visitors, fill = park_name))+
  geom_bar(stat = "identity", position = "dodge") #enables y variables in geom_bar, position separates the columns
```


```{r}

my_plot <- ggplot(visit_16, aes(state, visitors, fill = park_name))+
            geom_bar(stat = "identity", position = "dodge")

my_plot

ggsave(filename = "myplot.png", myplot, width = 10, height = 10, dpi = 300) # can determine output size and resolution in attributes
```


```{r}
bubbles <- ggplot(visit_16, aes(state, park_name))+
            geom_count()

bubbles
```

